name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Jest Tests
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

deploy:
    name: Build and Deploy Docs
    needs: test  # only runs if 'test' job passes
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install -g insomnia-documenter

      - name: Build documentation
        run: |
          mkdir -p build
          cp ./insomnia.json ./build/
          cd build
          npx insomnia-documenter --config insomnia.json
          cp ../insomnia.json ./

      - name: Backup old build
        run: |
          mkdir -p ~/old-build
          cp -r /data/www/casa-api-docs/* ~/old-build/ || true

      - name: Deploy new build
        run: |
          sudo rm -rf /data/www/casa-api-docs/*
          sudo cp -r ./build/* /data/www/casa-api-docs/
          sudo nginx -t
          sudo systemctl restart nginx.service